# print('Hello,world')
# print('Hey Jude, Don\'t make it bad')
# print('The sum is', 2+2+2+2)
# print('Hello, {}'.format('world'))
# name= ('Defne')
# print('Congratulations, {:s}, you won {:d}th Academy award.'.format(name, 90))
print('Coordinates of Babson: {lat}, {lon}'.format(lon='71.27W', lat='42.30N'))